# Generated by Django 5.2.12 on 2026-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sidebar_config',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Cấu hình Sidebar'),
        ),
    ]
