# Generated by Django 5.2.12 on 2026-04-08 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Tên dự án so sánh')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('base_file', models.FileField(upload_to='comparisons/base/', verbose_name='Văn bản gốc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dự án so sánh',
                'verbose_name_plural': 'Dự án so sánh',
            },
        ),
        migrations.CreateModel(
            name='DraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='comparisons/drafts/', verbose_name='Tệp dự thảo')),
                ('user_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú người dùng')),
                ('version_label', models.CharField(max_length=255, verbose_name='Nhãn phiên bản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='comparisons.comparisonproject')),
            ],
            options={
                'verbose_name': 'Phiên bản dự thảo',
                'verbose_name_plural': 'Phiên bản dự thảo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('Chương', 'Chương'), ('Điều', 'Điều'), ('Khoản', 'Khoản'), ('Điểm', 'Điểm'), ('Phụ lục', 'Phụ lục'), ('Vấn đề khác', 'Vấn đề khác')], max_length=20)),
                ('node_label', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comparisons.comparisonnode')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_nodes', to='comparisons.comparisonproject')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='comparisons.draftversion')),
            ],
            options={
                'verbose_name': 'Mục văn bản so sánh',
                'verbose_name_plural': 'Mục văn bản so sánh',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_to', to='comparisons.comparisonnode')),
                ('draft_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_from', to='comparisons.comparisonnode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='comparisons.comparisonproject')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='comparisons.draftversion')),
            ],
            options={
                'verbose_name': 'Ánh xạ so sánh',
                'verbose_name_plural': 'Ánh xạ so sánh',
                'unique_together': {('version', 'base_node')},
            },
        ),
    ]
