# Generated by Django 5.2.12 on 2026-04-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonproject',
            name='base_document_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên định danh văn bản gốc'),
        ),
        migrations.AddField(
            model_name='comparisonproject',
            name='draft_document_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên định danh văn bản dự thảo'),
        ),
    ]
