# Generated by Django 5.2.12 on 2026-04-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0002_comparisonproject_base_document_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonAIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('reference_check', 'Rà soát dẫn chiếu'), ('automated_report', 'Báo cáo tự động')], max_length=50)),
                ('content', models.TextField(verbose_name='Nội dung kết quả (JSON hoặc Markdown)')),
                ('agent_info', models.CharField(max_length=255, verbose_name='Thông tin Agent (Gemini, Qwen...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='comparisons.draftversion')),
            ],
            options={
                'verbose_name': 'Kết quả Phân tích AI',
                'verbose_name_plural': 'Kết quả Phân tích AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
