# Generated by Django 5.2.12 on 2026-04-08 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0003_comparisonairesult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonairesult',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='comparisons.draftversion'),
        ),
        migrations.CreateModel(
            name='StandaloneReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Tên phiên bản rà soát')),
                ('file', models.FileField(upload_to='comparisons/standalone/', verbose_name='Tệp văn bản')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rà soát độc lập',
                'verbose_name_plural': 'Rà soát độc lập',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comparisonairesult',
            name='standalone_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='comparisons.standalonereview'),
        ),
        migrations.AddField(
            model_name='comparisonnode',
            name='standalone_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='comparisons.standalonereview'),
        ),
    ]
