# Generated by Django 5.2.12 on 2026-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0004_alter_comparisonairesult_version_standalonereview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonnode',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Thuyết minh so sánh'),
        ),
        migrations.AddField(
            model_name='draftversion',
            name='explanation_sheet_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link Google Sheet thuyết minh'),
        ),
    ]
