# Generated by Django 5.2.12 on 2026-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comparisons", "0005_comparisonnode_explanation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparisonnode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("Phần", "Phần"),
                    ("Chương", "Chương"),
                    ("Mục", "Mục"),
                    ("Tiểu mục", "Tiểu mục"),
                    ("Điều", "Điều"),
                    ("Khoản", "Khoản"),
                    ("Điểm", "Điểm"),
                    ("Phụ lục", "Phụ lục"),
                    ("Vấn đề khác", "Vấn đề khác"),
                ],
                max_length=20,
            ),
        ),
    ]
