# Generated by Django 5.2.12 on 2026-03-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='agency_name',
            field=models.CharField(blank=True, help_text='Tên cơ quan, tổ chức chủ trì', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='headquarters_location',
            field=models.CharField(blank=True, help_text='Địa danh nơi cơ quan đóng trụ sở', max_length=200, null=True),
        ),
    ]
