# Generated by Django 5.2.12 on 2026-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_agency_name_document_headquarters_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='headquarters_location',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='agency_location',
            field=models.CharField(blank=True, help_text='Địa danh nơi đóng trụ sở', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='drafting_agency',
            field=models.CharField(blank=True, help_text='Tên cơ quan, tổ chức chủ trì', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='project_name',
            field=models.CharField(default='Dự thảo', max_length=500),
        ),
    ]
