# Generated by Django 5.2.12 on 2026-03-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_lead_nodeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='total_consulted',
            field=models.IntegerField(default=0, help_text='Tổng số cơ quan, tổ chức, cá nhân được lấy ý kiến'),
        ),
        migrations.AddField(
            model_name='document',
            name='total_feedbacks',
            field=models.IntegerField(default=0, help_text='Tổng số ý kiến nhận được'),
        ),
    ]
