# Generated by Django 5.2.12 on 2026-03-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_total_consulted_document_total_feedbacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='total_consulted',
            new_name='total_consulted_doc',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='total_feedbacks',
            new_name='total_feedbacks_doc',
        ),
    ]
