# Generated by Django 5.2.12 on 2026-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_rename_total_consulted_document_total_consulted_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentnode',
            name='node_type',
            field=models.CharField(choices=[('Điều', 'Điều'), ('Khoản', 'Khoản'), ('Điểm', 'Điểm'), ('Vấn đề khác', 'Vấn đề khác')], max_length=20),
        ),
    ]
