# Generated by Django 5.2.12 on 2026-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_documentnode_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentnode',
            name='node_type',
            field=models.CharField(choices=[('Chương', 'Chương'), ('Điều', 'Điều'), ('Khoản', 'Khoản'), ('Điểm', 'Điểm'), ('Phụ lục', 'Phụ lục'), ('Vấn đề khác', 'Vấn đề khác')], max_length=20),
        ),
    ]
