# Generated by Django 5.2.12 on 2026-03-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_notification_sender"),
        ("documents", "0009_documenttype_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="consulted_agencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="consulted_documents",
                to="core.agency",
                verbose_name="Các đơn vị được lấy ý kiến",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="issuance_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày văn bản phát hành lấy ý kiến"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="issuance_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Số văn bản phát hành lấy ý kiến",
            ),
        ),
    ]
