# Generated by Django 5.2.12 on 2026-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0010_document_consulted_agencies_document_issuance_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="issuance_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/issuance/",
                verbose_name="File văn bản phát hành",
            ),
        ),
    ]
