# Generated by Django 5.2.12 on 2026-03-31 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_document_issuance_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAppendix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Tên phụ lục")),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nội dung văn bản"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/appendices/",
                        verbose_name="Tệp đính kèm",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appendices",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phụ lục văn bản",
                "verbose_name_plural": "Phụ lục văn bản",
                "ordering": ["created_at"],
            },
        ),
    ]
