# Generated by Django 5.2.12 on 2026-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_documentappendix'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='google_sheets_url',
            field=models.URLField(blank=True, help_text='Link Google Sheets của dự thảo', max_length=1000, null=True),
        ),
    ]
