# Generated by Django 5.2.12 on 2026-04-03 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_google_sheets_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='lead',
        ),
        migrations.AddField(
            model_name='document',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='led_documents', to=settings.AUTH_USER_MODEL, verbose_name='Cán bộ chủ trì'),
        ),
    ]
