# Generated by Django 5.2.12 on 2026-03-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Tham số')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Giá trị')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cài đặt hệ thống',
                'verbose_name_plural': 'Cài đặt hệ thống',
            },
        ),
    ]
