# Generated by Django 5.2.12 on 2026-03-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên cơ quan/tổ chức')),
                ('category', models.CharField(choices=[('ministry', 'Bộ, cơ quan ngang Bộ'), ('local', 'Địa phương (UBND tỉnh/thành phố)'), ('organization', 'Sở, Ban, Ngành, Tổ chức, Đoàn thể'), ('citizen', 'Công dân, Doanh nghiệp'), ('other', 'Khác')], default='other', max_length=50, verbose_name='Phân loại hệ thống')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cơ quan/Chủ thể',
                'verbose_name_plural': 'Cơ quan/Chủ thể',
                'ordering': ['category', 'name'],
            },
        ),
    ]
