# Generated by Django 5.2.12 on 2026-03-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên phân loại')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả')),
                ('color', models.CharField(default='#405189', max_length=20, verbose_name='Mã màu hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục Phân loại Cơ quan',
                'verbose_name_plural': 'Danh mục Phân loại Cơ quan',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['agency_category__name', 'name'], 'verbose_name': 'Cơ quan/Chủ thể', 'verbose_name_plural': 'Cơ quan/Chủ thể'},
        ),
        migrations.AlterField(
            model_name='agency',
            name='category',
            field=models.CharField(choices=[('ministry', 'Bộ, cơ quan ngang Bộ'), ('local', 'Địa phương (UBND tỉnh/thành phố)'), ('organization', 'Sở, Ban, Ngành, Tổ chức, Đoàn thể'), ('citizen', 'Công dân, Doanh nghiệp'), ('other', 'Khác')], default='other', max_length=50, verbose_name='Phân loại hệ thống (Legacy)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='core.agencycategory', verbose_name='Phân loại cơ quan'),
        ),
    ]
