# Generated by Django 5.2.12 on 2026-03-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agencycategory_alter_agency_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencycategory',
            name='color',
        ),
    ]
