# Generated by Django 5.2.12 on 2026-04-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_agencycategory_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="category",
            field=models.CharField(
                default="other",
                max_length=50,
                verbose_name="Phân loại hệ thống (Legacy)",
            ),
        ),
    ]
