# Generated by Django 5.2.12 on 2026-03-22 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agency'),
        ('feedbacks', '0002_feedback_contributing_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Cơ quan góp ý chuẩn hóa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='core.agency'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contributing_agency',
            field=models.CharField(blank=True, help_text='Tên text tự nhập (Legacy)', max_length=500, null=True),
        ),
    ]
