# Generated by Django 5.2.12 on 2026-03-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0004_feedback_status_actionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="official_doc_number",
            field=models.CharField(
                blank=True,
                help_text="Số công văn của cơ quan góp ý",
                max_length=255,
                null=True,
            ),
        ),
    ]
