# Generated by Django 5.2.12 on 2026-03-30 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_notification_sender"),
        ("documents", "0011_document_issuance_file"),
        ("feedbacks", "0005_feedback_official_doc_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_number",
                    models.CharField(max_length=255, verbose_name="Số hiệu công văn"),
                ),
                ("official_date", models.DateField(verbose_name="Ngày công văn")),
                (
                    "attached_file",
                    models.FileField(
                        upload_to="consultation_responses/",
                        verbose_name="File đính kèm công văn",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_responses",
                        to="core.agency",
                        verbose_name="Đơn vị góp ý",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="documents.document",
                        verbose_name="Dự thảo liên quan",
                    ),
                ),
            ],
        ),
    ]
