# Generated by Django 5.2.12 on 2026-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_consultationresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationresponse',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='consultation_responses/', verbose_name='File đính kèm công văn'),
        ),
    ]
