# Generated by Django 5.2.12 on 2026-03-31 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0012_documentappendix"),
        ("feedbacks", "0007_alter_consultationresponse_attached_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="appendix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="documents.documentappendix",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="documents.documentnode",
            ),
        ),
    ]
