# Generated by Django 5.2.12 on 2026-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0008_feedback_appendix_alter_feedback_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="Lý do"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="content",
            field=models.TextField(verbose_name="Nội dung góp ý"),
        ),
    ]
