# Generated by Django 5.2.12 on 2026-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0010_feedbackassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='need_opinion',
            field=models.BooleanField(default=False, verbose_name='Cần xin ý kiến'),
        ),
    ]
