# Generated by Django 5.2.5 on 2026-04-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0011_feedback_need_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='need_opinion',
            field=models.TextField(blank=True, null=True, verbose_name='Cần xin ý kiến'),
        ),
    ]
